json.id @recipe.id
json.title @recipe.title
json.chef @recipe.chef
json.prep_time @recipe.prep_time
json.friendly_prep_time @recipe.friendly_prep_time
json.ingredients @recipe.ingredients
json.directions @recipe.directions
json.formatted_ingredients @recipe.formatted_ingredients
json.formatted_directions @recipe.formatted_directions
json.created_at @recipe.friendly_created_at
